version: "3"

services:
  cfgsetup:
    container_name: cfgsetup
    build: .
    depends_on:
      - cfgsvr1
    restart: "no"
    entrypoint: ["bash", "-c", "sleep 5 && ./setupConfig.sh"]

  cfgsvr1:
    container_name: cfgsvr1
    image: mongo:4.2
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - cfgsvr1:/data/db

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo:4.2
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2:/data/db

  cfgsvr3:
    container_name: cfgsvr3
    image: mongo:4.2
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - cfgsvr3:/data/db

volumes:
  cfgsvr1: {}
  cfgsvr2: {}
  cfgsvr3: {}
