version: "3"

services:
  shard2setup:
    container_name: shard2setup
    build: .
    depends_on:
      - shard2svr1
    restart: "no"
    entrypoint: ["bash", "-c", "sleep 5 && ./setupShard2.sh"]
  shard2svr1:
    container_name: shard2svr1
    image: mongo:4.2
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - shard2svr1:/data/db

  shard2svr2:
    container_name: shard2svr2
    image: mongo:4.2
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - shard2svr2:/data/db

  shard2svr3:
    container_name: shard2svr3
    image: mongo:4.2
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 50006:27017
    volumes:
      - shard2svr3:/data/db

volumes:
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}
